trigger: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  - repo: self

parameters:
  # - name: environment
  #   displayName: "Select Environment"
  #   type: string
  #   default: "dev"
  #   values:
  #   - dev
  #   - prod
  - name: executionMode
    displayName: 'Select Execution Mode'
    type: string
    default: 'BuildOnly'
    values:
      - BuildOnly
      - BuildAndDeploy

variables:
  ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
    ACR_SERVICE_CONNECTION: 'docker-dev-sp'
    AKS_SOURCE_BRANCH: 'dev'

  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    ACR_SERVICE_CONNECTION: 'docker-deepthought-sp'
    AKS_SOURCE_BRANCH: 'main'

  executionMode: ${{ parameters.executionMode }}
  DOCKER_IMAGE: 'senseai-ui'
  BRANCH_NAME: ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}

stages:
  - stage: Build
    displayName: 'Build - ${{ variables.BRANCH_NAME }}'
    condition: or(eq(variables['executionMode'], 'BuildOnly'), eq(variables['executionMode'], 'BuildAndDeploy'))
    variables:
      - group: senseai-ui-dev
    jobs:
      - job: Build
        displayName: 'Build and Push for - ${{ variables.BRANCH_NAME }}'
        steps:
          - script: echo "Branch Name is $(Build.SourceBranchName)"
            displayName: 'Check Branch Name'

          - task: Docker@2
            displayName: 'Login to Container Registry'
            inputs:
              command: 'login'
              containerRegistry: $(ACR_SERVICE_CONNECTION)

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: 'build'
              Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)'
              arguments: |
                --build-arg VITE_KEYCLOAK_SERVER_URL="$(VITE_KEYCLOAK_SERVER_URL)"
                --build-arg VITE_KEYCLOAK_REALM="$(VITE_KEYCLOAK_REALM)"
                --build-arg VITE_KEYCLOAK_CLIENT_ID="$(VITE_KEYCLOAK_CLIENT_ID)"
                --build-arg VITE_BASE_PATH="$(VITE_BASE_PATH)"
                --build-arg VITE_API_BASE_URL="$(VITE_API_BASE_URL)"
                --build-arg VITE_ALLOWED_HOSTS="$(VITE_ALLOWED_HOSTS)"
                --build-arg VITE_WS_BASE_URL="$(VITE_WS_BASE_URL)"
                --build-arg VITE_API_BASE_PATH="$(VITE_API_BASE_PATH)"
                --build-arg VITE_MICROSTRATEGY_BASE_URL="$(VITE_MICROSTRATEGY_BASE_URL)"
                --build-arg VITE_MICROSTRATEGY_PROJECT_ID="$(VITE_MICROSTRATEGY_PROJECT_ID)"
                --build-arg VITE_MICROSTRATEGY_DASHBOARD_ID="$(VITE_MICROSTRATEGY_DASHBOARD_ID)"
                --build-arg VITE_POWERBI_CLIENT_ID="$(VITE_POWERBI_CLIENT_ID)"
                --build-arg VITE_POWERBI_DEFAULT_WORKSPACE_ID="$(VITE_POWERBI_DEFAULT_WORKSPACE_ID)"
                --build-arg VITE_MAX_FILE_SIZE="$(VITE_MAX_FILE_SIZE)"
                --build-arg VITE_ALLOWED_FILE_TYPES="$(VITE_ALLOWED_FILE_TYPES)"
                --build-arg VITE_PYTHON_API_URL_DEV="$(VITE_PYTHON_API_URL_DEV)"
                --build-arg VITE_PYTHON_API_URL_PROD="$(VITE_PYTHON_API_URL_PROD)"
              tags: |
                $(Build.BuildId)
              repository: '$(DOCKER_IMAGE)'

          - task: Docker@2
            displayName: 'Push Docker Image'
            inputs:
              command: 'push'
              containerRegistry: '$(ACR_SERVICE_CONNECTION)'
              repository: '$(DOCKER_IMAGE)'
              tags: |
                $(Build.BuildId)
  - stage: UpdateManifest
    displayName: "Update Manifest in Aks_source Repo"
    variables:
      - group: ado_vars
    jobs:
     - job: UpdateManifest
       displayName: "Update Kubernetes Manifest"
       steps:
    
       - script: | 
          echo "Setting up Git authentication..."
          git config --global user.email "devops-bot@tigeranalytics.com"
          git config --global user.name "ADO Pipeline"
         displayName: "Configure Git Credentials"
    
       - script: |
          echo "Cloning Aks_source repo (branch: $(AKS_SOURCE_BRANCH)..."
          git clone --branch "$(AKS_SOURCE_BRANCH)" https://deepthought01:$(PAT_TOKEN)@dev.azure.com/deepthought01/deepthought/_git/Aks_source aks_source_repo
         displayName: "Clone Aks_source Repo"
         env:
          PAT_TOKEN: $(PAT_TOKEN)
    
       - script: |
          echo "Updating manifest with new image tag: $(Build.BuildId)"
          sed -i "s|azurecr.io/senseai-ui:[^ ]*|azurecr.io/senseai-ui:$(Build.BuildId)|g" aks_source_repo/Manifest_Senseaiui/manifest_senseaiui.yaml
         displayName: "Update Manifest File"
    
    
       - script: |
          cd aks_source_repo
          git remote set-url origin https://deepthought01:$(PAT_TOKEN)@dev.azure.com/deepthought01/deepthought/_git/Aks_source
          git add Manifest_Senseaiui/manifest_senseaiui.yaml
          git commit -m "Updated manifest with image tag $(Build.BuildId)"
          git push origin HEAD:$(AKS_SOURCE_BRANCH)
         displayName: "Commit & Push Updated Manifest"
         env:
          PAT_TOKEN: $(PAT_TOKEN)

          
           
           
         
